import { type IUser } from "./user-model";
import moment from 'moment';

export const mockUsers: IUser[] = [
    {
        id: "1",
        name: "Иван",
        surName: "Иванов",
        password: "password1", 
        fullName: "Иван Иванов",
        email: "ivan.ivanov@example.com",
        birthDate: moment("1990-05-15"),
        telephone: "+79123456789",
        employment: "frontend-разработчик",
        userAgreement: true,
    },
    {
        id: "2",
        name: "Мария",
        surName: "Петрова",
        password: "password2", 
        fullName: "Мария Петрова",
        email: "maria.petrova@example.com",
        birthDate: moment("1985-11-22"),
        telephone: "+79234567890",
        employment: "frontend-разработчик",
        userAgreement: true,
    },
    {
        id: "3",
        name: "Алексей",
        surName: "Сидоров",
        password: "password3", 
        fullName: "Алексей Сидоров",
        email: "alex.sidorov@example.com",
        birthDate: moment("1995-03-10"),
        telephone: "+79345678901",
        employment: "frontend-разработчик",
        userAgreement: false,
    },
    {
        id: "4",
        name: "Елена",
        surName: "Кузнецова",
        password: "password4", 
        fullName: "Елена Кузнецова",
        email: "elena.kuznetsova@example.com",
        birthDate: moment("1988-07-30"),
        employment: "frontend-разработчик",
        userAgreement: true,
    },
    {
        id: "5",
        name: "Дмитрий",
        surName: "Смирнов",
        password: "password5", 
        fullName: "Дмитрий Смирнов",
        email: "dmitry.smirnov@example.com",
        userAgreement: true,
    },
    {
        id: "6",
        name: "Ольга",
        surName: "Васильева",
        password: "password6", 
        fullName: "Ольга Васильева",
        email: "olga.vasilieva@example.com",
        birthDate: moment("1992-08-14"),
        telephone: "+79456789012",
        employment: "frontend-разработчик",
        userAgreement: true,
    },
    {
        id: "7",
        name: "Артем",
        surName: "Федоров",
        password: "password7", 
        fullName: "Артем Федоров",
        email: "artem.fedorov@example.com",
        birthDate: moment("1987-12-03"),
        telephone: "+79567890123",
        userAgreement: true,
    },
    {
        id: "8",
        name: "Анна",
        surName: "Морозова",
        password: "password8", 
        fullName: "Анна Морозова",
        email: "anna.morozova@example.com",
        birthDate: moment("1998-04-25"),
        employment: "frontend-разработчик",
        userAgreement: false,
    },
    {
        id: "9",
        name: "Сергей",
        surName: "Новиков",
        password: "password9", 
        fullName: "Сергей Новиков",
        email: "sergey.novikov@example.com",
        telephone: "+79678901234",
        employment: "frontend-разработчик",
        userAgreement: true,
    },
    {
        id: "10",
        name: "Татьяна",
        surName: "Павлова",
        password: "password10", 
        fullName: "Татьяна Павлова",
        email: "tatyana.pavlova@example.com",
        birthDate: moment("1983-09-17"),
        telephone: "+79789012345",
        employment: "frontend-разработчик",
        userAgreement: true,
    },
    {
        id: "11",
        name: "Андрей",
        surName: "Лебедев",
        password: "password11", 
        fullName: "Андрей Лебедев",
        email: "andrey.lebedev@example.com",
        birthDate: moment("1991-06-12"),
        telephone: "+79890123456",
        employment: "frontend-разработчик",
        userAgreement: true,
    },
    {
        id: "12",
        name: "Наталья",
        surName: "Соколова",
        password: "password12", 
        fullName: "Наталья Соколова",
        email: "natalia.sokolova@example.com",
        birthDate: moment("1986-02-28"),
        employment: "frontend-разработчик",
        userAgreement: true,
    },
    {
        id: "13",
        name: "Павел",
        surName: "Волков",
        password: "password13", 
        fullName: "Павел Волков",
        email: "pavel.volkov@example.com",
        employment: "frontend-разработчик",
        userAgreement: false,
    },
    {
        id: "14",
        name: "Екатерина",
        surName: "Козлова",
        password: "password14", 
        fullName: "Екатерина Козлова",
        email: "ekaterina.kozлова@example.com",
        birthDate: moment("1993-10-05"),
        telephone: "+79901234567",
        userAgreement: true,
    },
    {
        id: "15",
        name: "Михаил",
        surName: "Орлов",
        password: "password15", 
        fullName: "Михаил Орлов",
        email: "mikhail.orlov@example.com",
        birthDate: moment("1980-07-19"),
        telephone: "+79012345678",
        employment: "frontend-разработчик",
        userAgreement: true,
    },
];